#!/usr/bin/env python3
"""One-time build step: download the needed Outfit + DM Sans weights (latin woff2),
base64-inline them, and replace the Google Fonts <link> tags in index.html with
embedded @font-face rules. Makes index.html truly offline. Safe to re-run."""
import base64
import re
import urllib.request

HERE = "/Users/taylor/Desktop/Coding/Hydraulic Student Companion"
INDEX = HERE + "/index.html"
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

FAMILIES = [
    ("Outfit", [400, 500, 600, 700, 800]),
    ("DM Sans", [400, 500, 600, 700]),
]


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req) as r:
        return r.read()


def css_url(family, weights):
    fam = family.replace(" ", "+")
    w = ";".join(str(x) for x in weights)
    return f"https://fonts.googleapis.com/css2?family={fam}:wght@{w}&display=swap"


# Match each @font-face block, keep only the /* latin */ ones.
BLOCK = re.compile(
    r"/\*\s*latin\s*\*/\s*@font-face\s*\{([^}]*)\}", re.S)
WEIGHT = re.compile(r"font-weight:\s*(\d+)")
SRC = re.compile(r"url\((https://[^)]+\.woff2)\)")

faces = []
total = 0
for family, weights in FAMILIES:
    css = fetch(css_url(family, weights)).decode("utf-8")
    for m in BLOCK.finditer(css):
        body = m.group(1)
        wt = WEIGHT.search(body).group(1)
        url = SRC.search(body).group(1)
        data = fetch(url)
        total += len(data)
        b64 = base64.b64encode(data).decode("ascii")
        faces.append(
            "  @font-face {\n"
            f"    font-family: '{family}';\n"
            "    font-style: normal;\n"
            f"    font-weight: {wt};\n"
            "    font-display: swap;\n"
            f"    src: url(data:font/woff2;base64,{b64}) format('woff2');\n"
            "  }"
        )
        print(f"  {family} {wt}: {len(data)//1024} KB")

style = ("  <!-- Fonts embedded as woff2 data URIs (offline). Generated by embed_fonts.py. -->\n"
         "  <style id=\"embedded-fonts\">\n" + "\n".join(faces) + "\n  </style>")

html = open(INDEX, encoding="utf-8").read()

# Replace the three Google Fonts <link> lines (preconnect x2 + stylesheet).
link_block = re.compile(
    r'[ \t]*<link rel="preconnect" href="https://fonts\.googleapis\.com"[^\n]*\n'
    r'[ \t]*<link rel="preconnect" href="https://fonts\.gstatic\.com"[^\n]*\n'
    r'[ \t]*<link href="https://fonts\.googleapis\.com/css2[^\n]*\n')

if not link_block.search(html):
    raise SystemExit("Could not find the Google Fonts <link> block to replace.")

html = link_block.sub(style + "\n", html)
open(INDEX, "w", encoding="utf-8").write(html)
print(f"\nEmbedded {len(faces)} faces, {total//1024} KB raw woff2. index.html updated.")
